codecov:
  require_ci_to_pass: true

coverage:
  precision: 1
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        if_ci_failed: ignore
        only_pulls: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true
        if_ci_failed: ignore

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "scripts/"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "**/*.config.mjs"
  - "**/*.config.cjs"
  - "**/*.d.ts"
  - ".next/"
  - "public/"
